Use nvcr.io for dcgm-exporter and bump to v2.0-rc1 (from 1.7.2)
NVIDIA/deepops pull request #694
Opened 2020-10-08 18:42 UTC by supertetelman

* Use NGC instead of DockerHub
* Bump to 2.0 RC

2020-10-09 20:19 UTC, supertetelman commented
Before merging this I notcied that both `kubectl wait` and `helm install --wait` seem to hang and eventually timeout for no clear reason. In this scripts it will run until it hits the timeout, but if you open a new terminal and manually run the same command, the `Ready` condition is met and the wait immediately returns. Not sure if this is a Helm issue or an implementation issue.

2020-10-13 00:37 UTC, supertetelman commented
I've got this running now but there are three things that need to be addressed.

1. The upgrade from prometheus-operator to the new kube-prometheus-stack requires removing the old operator and ingress. When I do this I am running into the below error during upgrade/install,  it seems like something isn't getting cleaned up and it is still referencing the old operator.
```
I might need your help looking into this as I also was seeing a potentially related (or a missed file) error Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=30s: service "prometheus-operator-operator" not found
```

2. The docs still need to be updated.

3. The default configuration for ingress is `LoadBalancer`. This was not previously a problem even on systems with no LoadBalancer, the helm install was still running fine. However, now on my local systems that do not have a load balancer, the helm install changes and I had to manually change this. I'm not sure if we want to leave things as is, change our default configuration, or add some logic to our `deploy_ingress.sh` to detect metallb and reconfigure ingress appropriately.

2020-10-13 18:42 UTC, ajdecon requested changes
Overall this looks good, only making one request for a change so that we aren't editing the user's configuration. See inline comment.

2020-10-13 18:52 UTC, michael-balint reviewed
Tested - please address @ajdecon's suggestions so we can approve + merge.

2020-10-13 19:42 UTC, supertetelman commented on scripts/k8s/deploy_ingress.sh
> +fi
I hate to duplicate the config code, but this is a much cleaner implementation.

I  had figured that the user could remove the DYNAMIC flag if they didn't want it to be dynamic, but moving our example out of config altogether makes sense.

I introduced a new HELM_INGRESS_CONFIG global that can be used to override the workload example.

2020-10-13 19:59 UTC, ajdecon approved these changes
Updates LGTM!

2020-10-13 23:19 UTC, merged