Simple role for installing docker-ce.
NVIDIA/deepops pull request #860
Opened 2021-02-05 17:46 UTC by mantolini-nv

This is one of multiple PRs upcoming for an internal NVIDIA effort to add support for Scenario Runner to DeepOps.

We have built a POC and the internal documentation is here:
https://confluence.nvidia.com/display/TSEA/Constellation+Slurm+Cluster+for+Batch+Mode
POC repo: https://gitlab-master.nvidia.com/tse/constellation/constellationbatchpoc

The full list of planned PRs:
1. docker-ce role
2. rclone role
3. scenario-runner role and playbooks

Signed-off-by: Martin Antolini <mantolini@nvidia.com>

2021-02-05 18:17 UTC, ajdecon commented
@mantolini-nv : Apologies that I didn't remember this when we chatted, but for Docker installs in other contexts we are embedding the role from Kubespray. 

E.g., see the docker playbook: https://github.com/NVIDIA/deepops/blob/master/playbooks/container/docker.yml

Can you try using this playbook in your framework and see if it works for you, instead of adding a new role?

2021-02-05 21:16 UTC, mantolini-nv commented
@ajdecon I hd to write a new docker-ce role because I kept having problems with the main one. I can't remember the issue but I think it was either forcing a version or configuration that I didn't want. But my playbook changed a lot since that original decision, so I'll try it again.

2021-02-11 18:08 UTC, mantolini-nv commented
@ajdecon the playbook https://github.com/NVIDIA/deepops/blob/master/playbooks/container/docker.yml has a lot of kubespray stuff in it and it's failing for me since I don't want k8s. Is there a generic docker role that I'm missing? thanks!

2021-02-11 18:29 UTC, ajdecon commented
@mantolini-nv : Can you share the failures you're seeing? While we are piggybacking on the Kubespray docker role, we definitely use it outside a Kubernetes context, as in our [Grafana playbook](https://github.com/NVIDIA/deepops/blob/master/playbooks/slurm-cluster/grafana.yml) which is used on generic Slurm clusters.

2021-02-11 18:56 UTC, mantolini-nv commented
@ajdecon ah interesting, here is the error: 

mantolini@mantolini-drivesim:~/git/constellationbatchpoc$ ansible-playbook -i config/inventory.sae -l slurm-cluster playbooks/test.yml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
ERROR! vars file ../../submodules/kubespray/roles/kubespray-defaults/defaults/main.yaml was not found
Could not find file on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
mantolini@mantolini-drivesim:~/git/constellationbatchpoc$ 

and this is how I'm calling it from the playbook:

- include: container/docker.yml
  tags: docker
  vars:
    hostlist: "{{ slurm-master[0] }}"

thanks!

2021-02-24 00:42 UTC, ajdecon requested changes
Requesting changes on this to block merge as I think we figured out offline how to make the existing solution work for this use case.

Please ping me if there are still challenges and we should revisit this!

2021-06-16 22:48 UTC, ajdecon commented
Closing as obsolete, but let's discuss offline if this is still needed!

2021-06-16 22:48 UTC, closed without merging