Burnin container
NVIDIA/deepops pull request #929
Opened 2021-04-09 18:17 UTC by ctierneynv

Fixed pull request to reorganize and update BIT to use NGC container

2021-04-27 14:39 UTC, avolkov1 commented
I am reviewing this now.

2021-05-12 21:01 UTC, avolkov1 requested changes
There was one typo for command when running with singularity. Please fix.

The other comment was a suggestion to split the `CMD` variable assignment into multiple lines for better readability.

I tested the scripts by running multinode HPL with two DGX-1V 16G nodes using singularity (I fixed the typo when testing). Worked great.

2021-05-13 15:53 UTC, avolkov1 requested changes

2021-05-13 15:53 UTC, avolkov1 commented on workloads/bit/hpl/launch_hpl_experiment.sh
> +container="nvcr.io/nvidia/hpc-benchmarks:20.10-hpl"
This needs to be updated to latest HPL container: "nvcr.io/nvidia/hpc-benchmarks:21.4-hpl"

2021-05-13 16:28 UTC, avolkov1 approved these changes
Great! Approved.

2021-05-13 17:03 UTC, ajdecon approved these changes
Merging based on @avolkov1 approval

2021-05-13 17:04 UTC, merged